<a href="https://colab.research.google.com/github/abdurrahman16/Pandas-Data-Manipulation/blob/main/Pandas_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [6]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [7]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [25]:
#dictionary
temp={
    "Student_Name": ["Babban", "Akash"],
    "Age": [12,15]
}

In [29]:
df2= pd.DataFrame(temp)
df2

  Student_Name  Age
0       Babban   12
1        Akash   15

In [30]:
df['latitude']

0        34.19
1        34.40
2        33.69
3        33.64
4        33.57
         ...
16995    40.58
16996    40.69
16997    41.84
16998    41.80
16999    40.54
Name: latitude, Length: 17000, dtype: float64

In [34]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [35]:
df.columns[4]

'total_bedrooms'

In [38]:
df[['latitude','population']]

       latitude  population
0         34.19      1015.0
1         34.40      1129.0
2         33.69       333.0
3         33.64       515.0
4         33.57       624.0
...         ...         ...
16995     40.58       907.0
16996     40.69      1194.0
16997     41.84      1244.0
16998     41.80      1298.0
16999     40.54       806.0

[17000 rows x 2 columns]

In [41]:
 df[['latitude','population']].iloc[2:3]

   latitude  population
2     33.69       333.0

In [42]:
#series
s= pd.Series([1,2,3,5])

In [43]:
s

0    1
1    2
2    3
3    5
dtype: int64

In [44]:
dates= pd.date_range('20140221', periods=6)
dates

DatetimeIndex(['2014-02-21', '2014-02-22', '2014-02-23', '2014-02-24',
               '2014-02-25', '2014-02-26'],
              dtype='datetime64[ns]', freq='D')

In [45]:
date2=pd.date_range('today', periods=6)
date2

DatetimeIndex(['2025-09-15 01:29:55.369930', '2025-09-16 01:29:55.369930',
               '2025-09-17 01:29:55.369930', '2025-09-18 01:29:55.369930',
               '2025-09-19 01:29:55.369930', '2025-09-20 01:29:55.369930'],
              dtype='datetime64[ns]', freq='D')

In [50]:
import numpy as np

In [52]:
myran=np.random.randn(6,2)

In [53]:
myran

array([[-1.0489191 ,  1.04039096],
       [-0.67927947, -0.08283801],
       [-0.12530453,  1.09479648],
       [-0.28073138, -0.63798938],
       [-0.60233483, -0.15628088],
       [ 1.23242882, -2.40992852]])

In [57]:
mani= pd.DataFrame(myran, index=dates, columns=['Babu','Shadny'])

In [58]:
mani

                Babu    Shadny
2014-02-21 -1.048919  1.040391
2014-02-22 -0.679279 -0.082838
2014-02-23 -0.125305  1.094796
2014-02-24 -0.280731 -0.637989
2014-02-25 -0.602335 -0.156281
2014-02-26  1.232429 -2.409929

In [59]:
mani.to_csv('mani.csv')

In [60]:
df['housing_median_age'].value_counts()

housing_median_age
52.0    1052
36.0     715
35.0     692
16.0     635
17.0     576
34.0     567
33.0     513
26.0     503
18.0     478
25.0     461
32.0     458
37.0     437
15.0     416
19.0     412
28.0     400
27.0     397
24.0     389
31.0     384
30.0     384
20.0     383
23.0     382
29.0     374
21.0     373
14.0     347
22.0     323
38.0     318
42.0     308
39.0     302
44.0     296
43.0     286
13.0     249
40.0     249
45.0     235
41.0     232
10.0     226
11.0     208
5.0      199
46.0     196
12.0     192
8.0      178
47.0     175
9.0      172
4.0      161
7.0      151
48.0     135
6.0      129
50.0     112
49.0     111
2.0       49
3.0       46
51.0      32
1.0        2
Name: count, dtype: int64

In [61]:
df['housing_median_age']<20

0         True
1         True
2         True
3         True
4        False
         ...
16995    False
16996    False
16997     True
16998     True
16999    False
Name: housing_median_age, Length: 17000, dtype: bool

In [63]:
df[df['housing_median_age']<20]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
10,-114.60,33.62,16.0,3741.0,801.0,2434.0,824.0,2.6797,86500.0
...,...,...,...,...,...,...,...,...,...
16983,-124.19,41.78,15.0,3140.0,714.0,1645.0,640.0,1.6654,74600.0
16987,-124.21,41.77,17.0,3461.0,722.0,1947.0,647.0,2.5795,68400.0
16991,-124.23,41.75,11.0,3159.0,616.0,1343.0,479.0,2.4805,73200.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0